# Generated by Django 4.2.24 on 2025-09-30 13:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modbus', '0005_registertemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interval_type', models.CharField(max_length=10)),
                ('comparison_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=7)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('units_produced', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftEnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('total_energy_kwh', models.FloatField()),
                ('avg_power_kw', models.FloatField()),
                ('peak_power_kw', models.FloatField()),
                ('units_produced', models.IntegerField(blank=True, null=True)),
                ('energy_per_unit', models.FloatField(blank=True, null=True)),
                ('cost_per_unit', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField()),
                ('tariff_rate', models.FloatField(default=0.15)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modbus.modbusdevice')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.shiftdefinition')),
            ],
            options={
                'unique_together': {('shift', 'device', 'shift_date')},
            },
        ),
        migrations.CreateModel(
            name='EnergySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interval_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10)),
                ('total_energy_kwh', models.FloatField()),
                ('avg_power_kw', models.FloatField()),
                ('max_power_kw', models.FloatField()),
                ('min_power_kw', models.FloatField()),
                ('energy_cost', models.FloatField(blank=True, null=True)),
                ('tariff_rate', models.FloatField(default=0.15)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modbus.modbusdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp'], name='analytics_e_device__3dffa9_idx'), models.Index(fields=['timestamp', 'interval_type'], name='analytics_e_timesta_712576_idx')],
                'unique_together': {('device', 'timestamp', 'interval_type')},
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('metric_type', models.CharField(max_length=50)),
                ('actual_value', models.FloatField()),
                ('expected_value', models.FloatField()),
                ('deviation', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modbus.modbusdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp'], name='analytics_a_device__8a1b89_idx')],
            },
        ),
    ]
