# Generated by Django 4.2.24 on 2025-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdefinition',
            name='tariff_rate',
            field=models.FloatField(default=0.15),
        ),
    ]
