# Generated by Django 4.2.24 on 2026-04-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_shiftdefinition_tariff_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(unique=True)),
                ('ref_date', models.DateField()),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('forecast_json', models.JSONField()),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
    ]
