# Generated by Django 4.2.24 on 2025-09-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port', models.CharField(default='/dev/ttyUSB0', max_length=100)),
                ('address', models.IntegerField(default=1)),
                ('baud_rate', models.IntegerField(default=9600)),
                ('parity', models.CharField(choices=[('N', 'None'), ('E', 'Even'), ('O', 'Odd')], default='N', max_length=1)),
                ('stop_bits', models.IntegerField(default=1)),
                ('byte_size', models.IntegerField(default=8)),
                ('timeout', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModbusRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('uint16', 'Unsigned 16-bit'), ('int16', 'Signed 16-bit'), ('uint32', 'Unsigned 32-bit'), ('int32', 'Signed 32-bit'), ('float32', 'Float 32-bit')], default='uint16', max_length=10)),
                ('scale_factor', models.FloatField(default=1.0)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='modbus.modbusdevice')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('log_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modbus.modbusdevice')),
            ],
        ),
    ]
