# Generated by Django 4.2.24 on 2025-09-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0002_devicemodel_alter_modbusdevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdevice',
            name='grafana_dashboard_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='grafana_dashboard_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='last_grafana_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modbusregister',
            name='grafana_metric_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='modbusregister',
            name='visualization_type',
            field=models.CharField(choices=[('timeseries', 'Time Series'), ('gauge', 'Gauge'), ('stat', 'Stat')], default='timeseries', max_length=20),
        ),
    ]
