# Generated by Django 4.2.24 on 2025-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0003_modbusdevice_grafana_dashboard_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusregister',
            name='influxdb_field_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
