# Generated by Django 4.2.24 on 2025-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0004_modbusregister_influxdb_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.IntegerField()),
                ('data_type', models.CharField(choices=[('uint16', 'Unsigned 16-bit'), ('int16', 'Signed 16-bit'), ('uint32', 'Unsigned 32-bit'), ('int32', 'Signed 32-bit'), ('float32', 'Float 32-bit')], default='uint16', max_length=20)),
                ('scale_factor', models.FloatField(default=1.0)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('voltage', 'Voltage'), ('current', 'Current'), ('power', 'Power'), ('energy', 'Energy'), ('frequency', 'Frequency'), ('power_factor', 'Power Factor'), ('thd', 'THD')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'address'],
            },
        ),
    ]
