# Generated by Django 4.2.24 on 2025-10-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0005_registertemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyaggregate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyaggregate',
            name='device',
        ),
        migrations.RemoveField(
            model_name='energymeasurement',
            name='device',
        ),
        migrations.DeleteModel(
            name='RegisterTemplate',
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='application_type',
            field=models.CharField(choices=[('machine', 'Machine'), ('supply', 'Supply'), ('department', 'Department'), ('process', 'Process'), ('facility', 'Facility')], default='machine', help_text='Where this device is installed', max_length=20),
        ),
        migrations.AddField(
            model_name='modbusregister',
            name='energy_measurement_field',
            field=models.CharField(blank=True, help_text='Corresponding field name in EnergyMeasurement model', max_length=50),
        ),
        migrations.AlterField(
            model_name='modbusregister',
            name='category',
            field=models.CharField(choices=[('voltage', 'Voltage'), ('current', 'Current'), ('power', 'Power'), ('energy', 'Energy'), ('power_quality', 'Power Quality'), ('harmonics', 'Harmonics'), ('frequency', 'Frequency'), ('temperature', 'Temperature'), ('status', 'Status'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusregister',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Link to specific device instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='modbus.modbusdevice'),
        ),
        migrations.AlterField(
            model_name='modbusregister',
            name='device_model',
            field=models.ForeignKey(blank=True, help_text='Link to device model for predefined registers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_templates', to='modbus.devicemodel'),
        ),
        migrations.AddConstraint(
            model_name='modbusregister',
            constraint=models.UniqueConstraint(condition=models.Q(('device_model__isnull', False)), fields=('device_model', 'address'), name='unique_address_per_model'),
        ),
        migrations.AddConstraint(
            model_name='modbusregister',
            constraint=models.UniqueConstraint(fields=('device', 'address'), name='unique_address_per_device'),
        ),
        migrations.DeleteModel(
            name='DailyAggregate',
        ),
        migrations.DeleteModel(
            name='EnergyMeasurement',
        ),
    ]
