# Generated by Django 5.2.7 on 2025-10-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0006_alter_dailyaggregate_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modbusregister',
            name='unique_address_per_device',
        ),
    ]
