# Generated by Django 5.2.7 on 2025-10-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0007_remove_modbusregister_unique_address_per_device'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modbusregister',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'address'), name='unique_address_per_device'),
        ),
        migrations.AddConstraint(
            model_name='modbusregister',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device_model__isnull', False), ('device__isnull', True)), models.Q(('device_model__isnull', True), ('device__isnull', False)), _connector='OR'), name='register_must_have_one_parent'),
        ),
    ]
