# Generated by Django 4.2.24 on 2025-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0008_modbusregister_unique_address_per_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusregister',
            name='register_count',
            field=models.IntegerField(default=0, help_text='Number of registers to read (0 = auto-calculate from data_type)'),
        ),
        migrations.AddField(
            model_name='modbusregister',
            name='word_order',
            field=models.CharField(choices=[('high-low', 'High-Low'), ('low-high', 'Low-High')], default='high-low', help_text='Word order for multi-word registers (high-low or low-high)', max_length=10),
        ),
    ]
