# Generated by Django 4.2.24 on 2025-11-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0009_add_register_count_word_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdevice',
            name='parent_device',
            field=models.ForeignKey(blank=True, help_text='Parent device in the single-line diagram hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_devices', to='modbus.modbusdevice'),
        ),
    ]
