# Generated by Django 4.2.24 on 2025-11-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0010_add_parent_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdevice',
            name='device_type',
            field=models.CharField(choices=[('electricity', 'Electricity Analyzer'), ('flowmeter', 'Flowmeter')], default='electricity', help_text='Type of device: electricity analyzer or flowmeter', max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusregister',
            name='category',
            field=models.CharField(choices=[('voltage', 'Voltage'), ('current', 'Current'), ('power', 'Power'), ('energy', 'Energy'), ('power_quality', 'Power Quality'), ('harmonics', 'Harmonics'), ('frequency', 'Frequency'), ('temperature', 'Temperature'), ('flow', 'Flow'), ('pressure', 'Pressure'), ('heat', 'Heat'), ('density', 'Density'), ('status', 'Status'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
