# Generated by Django 5.2.9 on 2025-12-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0011_add_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdevice',
            name='application_type',
            field=models.CharField(choices=[('gen', 'Generator'), ('wapda', 'WAPDA'), ('solar', 'Solar'), ('dept', 'Department'), ('facility', 'Facility'), ('process', 'Process'), ('machine', 'Machine')], default='machine', help_text='Application type: Supply (gen/wapda/solar) or Load (dept/facility/process/machine)', max_length=20),
        ),
        migrations.AlterField(
            model_name='modbusdevice',
            name='device_type',
            field=models.CharField(choices=[('electricity', 'Electricity Analyzer'), ('flowmeter', 'Flowmeter'), ('temp_gauge', 'Temperature Gauge')], default='electricity', help_text='Type of device: electricity analyzer, flowmeter, or temperature gauge', max_length=20),
        ),
    ]
