# Generated by Django 5.2.9 on 2025-12-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0012_alter_modbusdevice_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdevice',
            name='department',
            field=models.CharField(blank=True, help_text="Department this device monitors (e.g., 'denim', 'washing', 'finishing', 'sewing')", max_length=100),
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='machine_type',
            field=models.CharField(blank=True, help_text="Type of machine or equipment (e.g., 'main_lt_panel', 'steam_flowmeter')", max_length=100),
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='process',
            field=models.CharField(blank=True, help_text="Process this device is associated with (e.g., 'denim', 'washing')", max_length=100),
        ),
    ]
