# Generated by Django 5.2.9 on 2025-12-16 18:47
# Schema migration - removes old fields after data migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0014_1_data_migration'),  # Run data migration first
    ]

    operations = [
        migrations.RemoveField(
            model_name='modbusdevice',
            name='department',
        ),
        migrations.RemoveField(
            model_name='modbusdevice',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='modbusdevice',
            name='process',
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='floor',
            field=models.CharField(choices=[('GF', 'Ground Floor'), ('FF', 'First Floor'), ('SF', 'Second Floor'), ('WF', 'Washing Floor'), ('none', 'N/A')], default='none', help_text='Floor location: GF (Ground Floor), FF (First Floor), SF (Second Floor)', max_length=10),
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='load_type',
            field=models.CharField(choices=[('LT01', 'Load Type 01'), ('LT02', 'Load Type 02'), ('MAIN', 'Main'), ('none', 'N/A')], default='none', help_text='Load type: LT01, LT02, or MAIN', max_length=10),
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='process_area',
            field=models.CharField(choices=[('denim', 'Denim'), ('finishing', 'Finishing'), ('washing', 'Washing'), ('sewing', 'Sewing'), ('general', 'General')], default='general', help_text='Process area: Denim, Finishing, Washing, Sewing', max_length=20),
        ),
    ]
