# Generated by Django 5.2.9 on 2025-12-15 09:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modbus', '0012_alter_modbusdevice_application_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfficiencyBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark_type', models.CharField(choices=[('best_day', 'Best Day'), ('best_week', 'Best Week'), ('best_month', 'Best Month'), ('average', 'Average'), ('median', 'Median'), ('custom', 'Custom')], help_text='Type of benchmark', max_length=20)),
                ('metric_name', models.CharField(help_text="Metric name (e.g., 'kwh_per_garment', 'kwh_per_unit')", max_length=50)),
                ('benchmark_value', models.FloatField(help_text='Benchmark value for this metric', validators=[django.core.validators.MinValueValidator(0)])),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('calculated_from_days', models.IntegerField(blank=True, help_text='Number of days of data used for calculation', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, help_text='Device-specific benchmark (null for overall benchmarks)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='modbus.modbusdevice')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_energy_kwh', models.FloatField(default=0)),
                ('avg_daily_energy_kwh', models.FloatField(default=0)),
                ('peak_power_kw', models.FloatField(default=0)),
                ('component_breakdown', models.JSONField(default=dict, help_text='Breakdown by component (lights, machines, HVAC, etc.) in kWh')),
                ('total_units_produced', models.IntegerField(blank=True, null=True)),
                ('efficiency_kwh_per_unit', models.FloatField(blank=True, help_text='Calculated kWh per unit (e.g., kWh/garment)', null=True)),
                ('total_cost', models.FloatField(default=0)),
                ('tariff_rate', models.FloatField(default=0.15)),
                ('data_completeness', models.FloatField(default=100.0, help_text='Percentage of expected data points available')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, help_text='Device-specific aggregate (null for overall)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_aggregates', to='modbus.modbusdevice')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of production')),
                ('units_produced', models.IntegerField(help_text='Number of units produced (e.g., garments)', validators=[django.core.validators.MinValueValidator(0)])),
                ('shift_type', models.CharField(choices=[('LT01', 'LT01'), ('LT02', 'LT02'), ('MAIN', 'MAIN'), ('full_day', 'Full Day')], default='full_day', help_text='Shift type for production', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='Device/process for which production is recorded', on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='modbus.modbusdevice')),
            ],
            options={
                'ordering': ['-date', 'device'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text="Metric name (e.g., 'kwh_per_garment')", max_length=50)),
                ('target_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], help_text='Period for this target', max_length=20)),
                ('period_start', models.DateField(help_text='Start of target period')),
                ('period_end', models.DateField(help_text='End of target period')),
                ('target_value', models.FloatField(help_text='Target value to achieve', validators=[django.core.validators.MinValueValidator(0)])),
                ('current_value', models.FloatField(default=0, help_text='Current achieved value', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_on_track', models.BooleanField(default=True, help_text="Whether we're on track to achieve target")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benchmark_used', models.ForeignKey(blank=True, help_text='Benchmark this target was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.efficiencybenchmark')),
                ('device', models.ForeignKey(blank=True, help_text='Device-specific target (null for overall targets)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='modbus.modbusdevice')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_energy_kwh', models.FloatField(default=0)),
                ('avg_power_kw', models.FloatField(default=0)),
                ('peak_power_kw', models.FloatField(default=0)),
                ('component_breakdown', models.JSONField(default=dict)),
                ('units_produced', models.IntegerField(blank=True, null=True)),
                ('efficiency_kwh_per_unit', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to='modbus.modbusdevice')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='reporting_d_date_51ab8b_idx'), models.Index(fields=['device', 'date'], name='reporting_d_device__109cb1_idx')],
                'unique_together': {('device', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='efficiencybenchmark',
            index=models.Index(fields=['device', 'benchmark_type'], name='reporting_e_device__a65ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='efficiencybenchmark',
            index=models.Index(fields=['metric_name', 'is_active'], name='reporting_e_metric__971528_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='efficiencybenchmark',
            unique_together={('device', 'benchmark_type', 'metric_name')},
        ),
        migrations.AddIndex(
            model_name='monthlyaggregate',
            index=models.Index(fields=['month'], name='reporting_m_month_13657f_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyaggregate',
            index=models.Index(fields=['device', 'month'], name='reporting_m_device__7edb02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyaggregate',
            unique_together={('device', 'month')},
        ),
        migrations.AddIndex(
            model_name='productiondata',
            index=models.Index(fields=['device', 'date'], name='reporting_p_device__1e7545_idx'),
        ),
        migrations.AddIndex(
            model_name='productiondata',
            index=models.Index(fields=['date'], name='reporting_p_date_336f07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productiondata',
            unique_together={('device', 'date', 'shift_type')},
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['period_start', 'period_end'], name='reporting_t_period__e5c197_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['is_on_track'], name='reporting_t_is_on_t_1d27bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('device', 'metric_name', 'target_period', 'period_start')},
        ),
    ]
