# Generated by Django 5.2.9 on 2025-12-16 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus', '0014_remove_modbusdevice_department_and_more'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Equipment name (e.g., 'Finishing Lines', 'Exhaust Fans GF')", max_length=200)),
                ('equipment_type', models.CharField(choices=[('production_line', 'Production Line'), ('exhaust_fan', 'Exhaust Fan'), ('highbay', 'Highbay'), ('other', 'Other')], help_text='Type of equipment', max_length=20)),
                ('process_area', models.CharField(choices=[('denim', 'Denim'), ('finishing', 'Finishing'), ('washing', 'Washing'), ('sewing', 'Sewing'), ('packing', 'Packing'), ('cutting', 'Cutting'), ('general', 'General')], default='general', help_text='Process area this equipment belongs to', max_length=20)),
                ('location', models.CharField(choices=[('GF', 'Ground Floor'), ('FF', 'First Floor'), ('SF', 'Second Floor'), ('WF', 'Washing Floor')], help_text='Floor location', max_length=10)),
                ('quantity', models.IntegerField(default=1, help_text='Number of units (QTY)', validators=[django.core.validators.MinValueValidator(0)])),
                ('power_per_unit_kw', models.FloatField(default=0, help_text='Power per unit in kW', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_load_kw', models.FloatField(default=0, help_text='Total load (kW × QTY)', validators=[django.core.validators.MinValueValidator(0)])),
                ('shift_hours', models.FloatField(default=8.0, help_text='Shift duration in hours')),
                ('daily_kwh', models.FloatField(blank=True, help_text='Daily consumption in kWh', null=True)),
                ('monthly_kwh', models.FloatField(blank=True, help_text='Monthly consumption in kWh', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['process_area', 'location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the dashboard entry')),
                ('kwh_generated', models.FloatField(blank=True, help_text='KWH Generated', null=True)),
                ('kw_avg', models.FloatField(blank=True, help_text='KW Average', null=True)),
                ('kw_peak', models.FloatField(blank=True, help_text='KW Peak', null=True)),
                ('avg_flow_tons_per_hr', models.FloatField(blank=True, help_text='Average Flow (Tons/Hrs)', null=True)),
                ('husk_kgs', models.FloatField(blank=True, help_text='Husk (Kgs)', null=True)),
                ('steam_tons', models.FloatField(blank=True, help_text='Steam (Tons)', null=True)),
                ('wastage_kg', models.FloatField(blank=True, help_text='Wastage (Kg)', null=True)),
                ('gas_availability', models.BooleanField(blank=True, help_text='Gas Availability', null=True)),
                ('gen_set_from', models.DateTimeField(blank=True, help_text='Gen-Set From time', null=True)),
                ('gen_set_to', models.DateTimeField(blank=True, help_text='Gen-Set To time', null=True)),
                ('gen_set_hours', models.FloatField(blank=True, help_text='Gen-Set Hours', null=True)),
                ('dg_engine', models.CharField(blank=True, help_text='DG Engine identifier', max_length=100)),
                ('downtime', models.FloatField(blank=True, help_text='Downtime in hours', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyaggregate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='daily_units_kwh',
            field=models.FloatField(blank=True, help_text='Daily units consumed in kWh (from meter difference)', null=True),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='Whether this data represents overtime hours'),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='meter_reading',
            field=models.FloatField(blank=True, help_text='Raw meter reading value', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyaggregate',
            unique_together={('device', 'date', 'is_overtime')},
        ),
        migrations.AddIndex(
            model_name='dailyaggregate',
            index=models.Index(fields=['is_overtime'], name='reporting_d_is_over_f28a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['equipment_type', 'process_area'], name='reporting_c_equipme_23a818_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['location'], name='reporting_c_locatio_4243c1_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityload',
            index=models.Index(fields=['is_active'], name='reporting_c_is_acti_6dd290_idx'),
        ),
        migrations.AddIndex(
            model_name='engineeringdashboard',
            index=models.Index(fields=['date'], name='reporting_e_date_80c945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='engineeringdashboard',
            unique_together={('date',)},
        ),
    ]
